- id: doi:10.1109/IGARSS52108.2023.10282851
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2023-10-20
  image: images/mimrf_bfm.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/hvak/MIMRF-BFM
    - type: link
      text: Poster
      link: https://hvak.io/files/igarss_poster_final.pdf
    - type: link
      text: arXiv
      link: https://arxiv.org/abs/2402.05045
  repo: hvak/MIMRF-BFM
- id: doi:10.1109/FUZZ-IEEE60900.2024.10611865
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2024-08-05
  image: images/bi-michi.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/hvak/Bi-MIChI
    - type: link
      text: arXiv
      link: https://arxiv.org/abs/2409.03212
  repo: hvak/Bi-MIChI
- id: doi:10.1109/ITSC58415.2024.10920115
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2024-09-24
  image: images/mambast.png
  buttons:
    - type: source
      text: Repo
      link: https://github.com/XiangboGaoBarry/MambaST
    - type: link
      text: arXiv
      link: https://arxiv.org/abs/2408.01037
  repo: XiangboGaoBarry/MambaST
- id: doi:10.23919/ICCAS63016.2024.10773333
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2024-10-29
  image: images/ar-net.png
- title: "Temporal CFT: Multi-Temporal Cross-Modality Fusion Transformer for Multispectral Video Object Detection"
  date: 2023-10-01
  image: images/temporal_cft.png
  authors:
    - Srikar Varaganti
    - Asiegbu Miracle Kanu-Asiegbu
    - Xiaoxiao Du
  publisher: IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)
  link: https://xiaoxiaodu.net/wp-content/uploads/2024/01/IROS_Poster_Abstract_2023__Srikar_-3.pdf
  buttons:
    - type: link
      text: Poster
      link: https://xiaoxiaodu.net/wp-content/uploads/2024/01/IROS2023_Poster_Srikar.pdf
- title: "MIC-AQT: Improving Domain Adaptive Object Detection of Adversarial Query Transformers with Masked Image Consistency"
  date: 2023-10-01
  image: images/mic_aqt.png
  authors:
    - Peter Stratton
    - Xiaoxiao Du
  publisher: IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)
  link: https://xiaoxiaodu.net/wp-content/uploads/2024/01/IROS_Poster_Abstract_2023-1.pdf
  buttons:
    - type: link
      text: Poster
      link: https://xiaoxiaodu.net/wp-content/uploads/2024/01/IROS2023_Poster_Peter.pdf