- id: doi:10.1109/IGARSS52108.2023.10282851
  type: paper
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2023-10-20
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Code Repo
      link: https://github.com/hvak/MIMRF-BFM
  repo: hvak/MIMRF-BFM
- id: doi:10.1109/FUZZ-IEEE60900.2024.10611865
  type: paper
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2024-08-05
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Code Repo
      link: https://github.com/hvak/Bi-MIChI
  repo: hvak/Bi-MIChI